---
rules:

- name: close_issues_older_than_2_days
  rule: close_outdated_issues
  options:
    # ISO 8601 duration
    older_than: P2D
    # Optional, apply label when closing
    apply_label: inactive
    # Optional, leave a comment when closing
    add_comment: |
      Sorry, closing the issue as its older than 2 days

- name: close_outdated_prs_older_than_20_days
  rule: close_outdated_pr
  options:
    # ISO 8601 duration
    older_than: P20D
    # Optional, apply label when closing
    apply_label: inactive
    # Optional, leave a comment when closing
    add_comment: |
      Sorry, closing the pr as its older than 20 days

- name: pr_matches_format
  rule: pr_format
  options:
    # Array of case-insensitive regular expressions
    # TODO:
    #   Decide on multi-line flag, escaping special characters, full vs partial match and other specific regex behaviors
    #   Behavior with multiple commits on a PR (squash commits, merge commits, etc)
    #   Matching commit bodies vs PR title vs PR body
    match_title:
      - "^#\\d+"
    # match_commit: ...
    # match_body: ...
    apply_label: invalid
    add_comment: |
      Sorry, PRs must follow conventions:
      1. Title must start with ticket number - #123 ...

- name: pr_size
  rule: pr_size_check
  options:
    strategy:
      - lines: 100
        files: 10
        apply_label: size-small
      - lines: 200
        files: 20
        apply_label: size-medium
      - apply_label: size-large
        add_comment: |
          Your PR is too large
